beyondhb1079/s4us

package.json, src/config/constants.js, src/pages/About.jsx, src/pages/Contact.jsx
- can be found in src/config/constants.js
=> refactored brand name

src/pages/About.jsx
{site name} will get replace once i refactor the brand name.
=> updated about text for edwin

.github/workflows/audit.yml, .github/workflows/auto-assign-project.yml
This will automatically add new issues/PRs to the [project view](https://github.com/beyondhb1079/s4us/projects/1).
Also auto assigns dependabot PRs to the Dependabot Updates column.
=> Auto assign new issues and PRs to project

.gitignore, package.json, src/components/LoginDialog.jsx, src/models/Scholarship.ts, src/pages/ScholarshipDetails.jsx, src/pages/ScholarshipDetails.test.jsx, src/testdata/scholarships.js, tsconfig.json, yarn.lock
Also added a prototype Scholarship class.
Fixes #73 
Please leave a comment on anything you find confusing or want to learn more about
=> Add TypeScript to the project

src/components/FilterDropdown.jsx, src/components/ScholarshipList.jsx, src/components/ScholarshipsList.test.jsx, src/pages/Scholarships.test.jsx
=> Add scholarships page tests

.github/workflows/validate.yml, .gitignore, firebase.json, package.json, src/models/FirestoreModel.test.ts, src/models/FirestoreModel.ts, src/models/Model.ts, src/models/db.ts, yarn.lock
The `FirestoreModel` class does the heavy lifting! The subclasses just need to implement a friendlier contructor.
=> Create base model interface and Firestore model class

.github/dependabot.yml
I feel like daily is too much now :/...
=> Change cadence back to weekly

src/components/Header.jsx
Context: https://github.com/beyondhb1079/s4us/security/code-scanning/5?query=ref%3Arefs%2Fheads%2Fmain
=> Fix code scanning alert

src/components/AboutCard.jsx, src/pages/About.jsx
Also made some structural improvements to the About page.  
There's still some things left to be done though (e.g. using `<Typography>` elements instead of raw `<h*>` elements and cleaning up the page to match current design).
Fixes #9
=> About Us: Josue

src/types/ScholarshipAmount.test.ts, src/types/ScholarshipAmount.ts
=> ScholarshipAmount type

src/components/ScholarshipList.jsx, src/models/Scholarships.test.ts, src/models/Scholarships.ts, src/pages/ScholarshipDetails.jsx, src/pages/ScholarshipDetails.test.jsx, src/pages/Scholarships.test.jsx
I figured out how to export Sheets data to Firestore. Let's support the scholarship amount type when we talk to Firestore now.
=> Support scholarship amount type

src/components/ScholarshipAmountField.jsx, src/types/AmountType.ts, src/types/ScholarshipAmount.test.ts, src/types/ScholarshipAmount.ts
I think this is a little more clearer
=> Rename "Full Ride" to "Full Tuition"

src/components/ScholarshipList.jsx, src/pages/ScholarshipDetails.jsx, src/pages/ScholarshipDetails.test.jsx
Before: https://dreamerscholars.web.app/scholarships/2HuigLKDmWmxi7h8PJQi
After: https://s4us-pr-206.onrender.com/scholarships/2HuigLKDmWmxi7h8PJQi
I also updated the detail page to use **Typography** and added an **Apply** button that takes you to the website. We're probably going to change this later when we have a final design
=> Use white-space: pre-line to output description as given

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
This should make it easier to file bug reports and feature requests and easier to write more descriptive pull requests.
=> Add issue and pull request templates

src/App.jsx, src/pages/ScholarshipDetails.jsx, src/pages/Scholarships.jsx
Set's the title of the page, which appears in the browser tab/window name.
Fixes #208. See that issue for context.
I've double checked the tab titles on Chrome on my laptop and on my phone.
1. Navigate to https://s4us-pr-211.onrender.com.
2. Click around.
3. Notice how your browser tab/window name changes as the page changes.
4. If you're on a mobile device, try sharing the page. You'll likely see the new titles as well.
=> Set page titles

.github/workflows/validate.yml
I changed the `prettier --check` step to print the diff on failure.
This'll make it easier to make small edits to files directly from GitHub.
On this PR 😃 
See the failure log in [this check](https://github.com/beyondhb1079/s4us/pull/229/checks?check_run_id=1445635291)
=> On style workflow action, show the diff of what's wanted on failure

.github/workflows/validate.yml
This PR modifies our **Validation** workflow to utilize dependency caching so that `yarn install` runs faster for jobs reusing the same dependencies another job already caches.
See [Caching dependencies to speed up workflows](https://docs.github.com/en/free-pro-team@latest/actions/guides/caching-dependencies-to-speed-up-workflows).
Currently our required **Validation** workflows take on the order of 2.5-3 minutes or so, which doesn't really allow for quick turnaround time when you make a small fix and push. This should speed things up a bit by caching yarn dependencies and reusing them when available. Namely, we should start seeing feedback on these checks about 20-30s sooner.
With this PR. 
Check how long all the **Validation** jobs take on another PR that doesn't use the cache: …
=> Cache dependencies for faster workflow runs

package.json, src/App.jsx, src/components/ScholarshipsMadeSimple.jsx, src/lib/testing.ts, src/models/Scholarships.test.ts, src/models/base/FirestoreCollection.test.ts, src/models/base/FirestoreModel.test.ts, src/pages/ScholarshipDetails.test.jsx, src/pages/Scholarships.test.jsx
- Refactored common Firebase test app setup
- Additionally introduced a parameter for specifying rules and defaulted to open rules
This'll help reduce the boilerplate in setting up a test app and also help us test Firestore requests without needing to set up auth.
This is tangentially related to #178.
Several tests use this.
=> Refactor test app setup

src/components/ScholarshipList.jsx
Helps with #154 
1. Go to https://s4us-pr-300.onrender.com/scholarships.
2. Try sharing a scholarship
=> Extract common share functionality variables

src/lib/experiments.test.ts, src/lib/experiments.ts
Creates a simple experiment library so we can hide functionality/features behind experiments until they're ready for release. E.g.
```jsx
return <...>
// other things
{experiments.showExtendedBlahMenu && ...}
<...>
```
If that feature isn't fully baked then you can still preview it by adding `?showExtendedBlahMenu` to the end of the URL.
Fixes #291 
Unit tests have been added.
=> Add an experiments library

package.json, src/components/ScholarshipList.jsx, src/components/ShareDialog.jsx, src/theme.js, yarn.lock
- Share dialog for sharing a scholarship via the interwebs.
- Can be a reusable component for sharing web by passing URL and Name, by using the ` ShareDialog.jsx` component
Intended to fix noted issue #154 [enhancement]
- Tested sharing via email and linkedIn but have not tested others as I don't have an account with Facebook and the other sharable services
- Will need to test for sharing other links instead of the scholarships
- Verified that the name and link of scholarships are fully functional and correct
These changes are on PR link and can be interacted -> [here](https://s4us-pr-227.onrender.com)
Steps : 
1 -> click the share icon
2 -> notice the scholarship you are sharing on the dialog
3 -> select the inter web interface that you want to share and test that it is working and the …
=> Share Dialog

src/models/Scholarships.ts, src/pages/ScholarshipForm.jsx
Adds author id and email to scholarship when they submit form. 
Fixes #290
On laptop using firefox and firebase emulator. 
1. Click the `https://s4us-pr-NUMBER.onrender.com` URL **render[bot]** left in the comment below.
2. submit a scholarship
3. check scholarship added in firestore
=> track user id and email

src/pages/About.jsx
Created a summary for Job Hernandez(ie., me) in About.jsx.
=> Created Job's summary [issue 347]

README.md, src/components/FilterBar.jsx
Check out the updated README: https://github.com/beyondhb1079/s4us/blob/readme/README.md
Please [leave comments and suggestions](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/reviewing-proposed-changes-in-a-pull-request)
=> Update README with setup instructions

firestore.rules
Restricts public reads to the scholarships collection.
Firebase has been sending me emails saying:
```
[Firebase] Your Cloud Firestore database has insecure rules
```
Existing Firestore rules test should test these changes.
=> Only allow reads for the scholarships collection

src/pages/About.jsx, src/pages/Scholarships.jsx
added simple pagination component; I had the understanding that adding functionality for the pagination component was a separate issue so this all I did. I may be wrong though.
=> Basic pagination component

.github/pull_request_template.md
I'm not sure if the template instructions are clear enough so I've tried to make them clearer and slightly simpler.
=> Update pull_request_template.md with hopefully clearer language

firestore.indexes.json, src/models/Scholarships.ts, src/pages/UserHome.jsx
I added functionality for fetching user scholarships. 
this was completed to display the scholarships that the user adds.
Fixes #
I did 'yarn start' and there were no errors.
- [x ] Bug fix (non-breaking change which fixes an issue)
- [ x] New feature (non-breaking change which adds functionality)
- [ x] User visible change (users will notice UI or functional changes)
2.
=> added functionality for fetching user scholarships.

src/models/Scholarships.test.ts
I just noticed we forgot to uncomment this in #343 before it was merged. I think we thought it was a race condition but it might have just been an OS/CPU issue.
Existing tests.
=> Uncomment commented out scholarships tests

src/models/base/FirestoreCollection.ts, src/models/base/FirestoreModel.ts, src/pages/ScholarshipDetails.jsx, src/pages/Scholarships.jsx, src/pages/UserHome.jsx
I just learned that instead of wrapping a promise around a promise to create a promise with a different result type you can just use `.then()` to transform the result type. E.g.
Before 
```js
return new Promise((resolve, reject) => {
somePromise
.then((result) => resolve(someTransformation(result)))
.catch(reject);
});
```
After:
```js
return somePromise.then((result) => someTransformation(result))
```
Existing tests cover most changes
2.
=> Promise refactors

package.json, yarn.lock
Temporary alternative to #410 while the test failures there get figured out.
Check the test and audit checks.
=> Fix audit issue through a yarn resolution

.github/workflows/dependabot-autoapprove.yml
Our noisiest PRs are the ones commented by our auto-approve bot and dependabot:
https://github.com/beyondhb1079/s4us/pulls?q=is%3Apr+is%3Aclosed+sort%3Acomments-desc
We'll see if this works on the next dependency updates run 🤷
=> Reduce bot noise on dependabot PRs

src/pages/UserHome.jsx
- Removed strange left padding on the overall page
- Switched white sections to use the Paper component with outlined edges and rounded corners
- Removed the minHeight from the top section, waiting instead on whenever we get that image added
- Fixed uneven padding/margin values (in general you want the padding/margin to be the same on all sides, or at least on opposite sides)
- Used [CSS Media Queries](https://material-ui.com/customization/breakpoints/#css-media-queries) to minimize padding/margin on mobile devices where screen real estate is more precious.
- Added + icon for **Add Scholarship** button
Fixes #312
Inspecting the page with the browser for various devices.
1. Go to https://s4us-pr-443.onrender.com.
2. Login.
3. Notice the changes.
4. Repeat on mobile screen (either via a …
=> Fix user home page styling

.github/workflows/dependabot-autoapprove.yml
I think the issue was I needed to use `github.pulls` instead of `github.pullReviews`.
I also simplified the code a bit to use promises and to write the bot comment when the review is created.
=> Fix autoapprove dependabot workflow issue

.gitignore, package.json, src/components/ScholarshipListCard.test.jsx, src/pages/Scholarships.jsx, src/pages/UserHome.jsx, yarn.lock
- Upgraded `eslint-config-prettier`, which absorbs some of the `prettier/*` extensions.
- Simplified ESLint config a bit
- Fixed present lint issues
- Configured `yarn lint` to use ESLint's cache. This should make `yarn lint` faster the next time we run them.
I'm a bit bothered by how long it takes to run the lint check :P
Ran `yarn lint` locally a few times under different scenarios on my computer:
- Without cache: roughly 20 seconds
- With cache, no changes: roughly 2.5 seconds
- With cache, single file changed: roughly 10 seconds
=> Minor ESLint improvements and fixes

package.json, src/components/HomeSection.jsx, src/components/ScholarshipDetailCard.jsx, src/components/ScholarshipListCard.jsx, src/models/Scholarships.test.ts, src/models/Scholarships.ts, src/pages/ScholarshipDetails.test.jsx, src/theme.js, src/types/ScholarshipEligibility.ts, yarn.lock
Scholarship details page styling to reflect the figma design. 
Added support for different eligibility sections such as GPA, Demographics and tags. Also supports states. 
Fixes #358 
On laptop using Firefox
1. Go to https://s4us-pr-476.onrender.com/scholarships.
2. Click on any scholarship to check the styling
=> Scholarship details styling

.gitignore, src/components/HomeSection.jsx, src/components/HomeSection.test.jsx
Simple tests for the HomeSection component i.e. issue #391.
I will add more tests. I just wanted to commit and start contributing to DreamScholars.
I wanted to get a review on the simple test I did because I have not tested web sites before, but I am reading a tutorial right now.
thanks.
`yarn start` and `yarn test` works.
=> HomeSection Tests

src/components/HomeSection.test.jsx
just fixed a small typo. So I didn’t test it.
=> Fixed typo

src/config/constants.js, src/pages/Contact.jsx
added a simple link to a a google form for subscription purposes.
Fixes #
I ran `yarn start` and everything was as expected.
=> Added Google Forms for subscriptions.

src/components/ProfileDropdown.jsx, src/config/constants.js, src/lib/experiments.test.ts, src/lib/experiments.ts
Helps with #507. I meant to do this earlier when I submitted #296. This is how we can guard not-yet-ready changes. I tried to refactor things such that adding an experiment is as simple as:
1. Adding a line in `experiments.ts` to create experiment X.
2. Importing `experiments` in the file that's going to use the experiment.
3. Guarding experimental code with `experiments.X`.
We might change the experiments library code later as we find other needs.
On localhost by setting and not setting the `expShowFullProfileMenu=1` in the URL query string.
1. Go to https://s4us-pr-506.onrender.com.
2. Log in.
3. Click the profile dropdown menu on the top right.
4. Take note of how it looks.
5. Now go to https://s4us-pr-506.onrender.com?expShowFullProfileMenu=1.
6. Click the profile dropdown menu on the …
=> use experiments library for showing full profile menu

.github/workflows/audit.yml, .github/workflows/ci.yml, .github/workflows/validation.yml
Fixes #517. See the issue for context. Basically, the new audit check for PRs that touch `yarn.lock` is to make sure they don't introduce any **new** vulnerabilities instead of ensuring there are **no** vulnerabilities. The old audit check will continue to run as part of the CI workflow.
Temporarily commented out the `yarn.lock` hook and had it run against this PR.
=> Improve audit checks for PRs

src/components/FilterBar.jsx, src/components/ScholarshipList.jsx, src/lib/sortOptions.test.ts, src/lib/sortOptions.ts, src/pages/Scholarships.jsx
I noticed there was a bit of a discrepancy in how we store/share sorting option info so I unified it in one place.
I tried it on the Render page.
1. Go to https://s4us-pr-559.onrender.com/scholarships.
2. Try the sorting options out.
=> Unify sorting options info

.gitignore, src/pages/Contact.jsx
renamed the branch. and deleted the firebase stuff. it wasnt needed. i did `yarn start` and everything worked fine.
=> Fix broken links

src/components/ScholarshipDetailCard.jsx
Styled the scholarship detail page so the card aspect can be seen. 
Fixes #358 
local host on laptop
1. Go to https://s4us-pr-566.onrender.com/scholarships.
2. Click on any scholarship
3. Notice the details are surrounded, giving a card aspect
=> Scholarship Detail Card Aspect

src/pages/About.jsx
removed old paragraphs and added a new one based on the figma design. Styling is a different issue so I did not style it.
I did `yarn start` and everything looked good.
=> update about page paragraphs

src/components/FilterBar.jsx, src/lib/experiments.ts
Added experiment guards to hide Grade filter and Major filter since they aren't fully functional yet.
Fixes #507 
1. Go to https://s4us-pr-569.onrender.com/scholarships.
2. notice how the Grade filter and the Major filter are hidden
=> experiment guards for GradeFilter and MajorFilter

src/components/ScholarshipsMadeSimple.jsx, src/pages/About.jsx, src/pages/PublicHome.jsx
Updated paragraphs in home page and the about me text for Sergio. 
Fixes #284 & #12 
On laptop using Firefox. 
1. Make sure you are logged out and go to https://s4us-pr-568.onrender.com.
2. Visit https://s4us-pr-568.onrender.com/about for updated paragraphs
=> Home Page paragraphs & Sergio about me description

src/models/base/FirestoreModel.ts, src/models/base/Model.ts
We're not using this so let's remove it. It can be re-added later if needed. Fixes #92
=> Remove the unused Model.subscribe() function

.github/workflows/approvals.yml
- Added [`--ignore-all-space`](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---ignore-all-space) to the diffing command. We don't need to worry about whitespace because the style check takes care of this.
- Increased the number of allowed deletions/insertions after approval.
- Fixed the link to this file in the bot comment.
In #596 the bot dismissed the PR approval because there were 72 insertions and 82 deletions since I last approved it. In reality, if you ignore the whitespace it was only 4 insertions and 13 deletions. 4 insertions is nothing! And two of those insertions were due to prettier replacing a 3 liner with a 1 liner now that those sections were indented two less spaces. If we ignore the prettier changes it was really just 2 insertions and 7 deletions, which is …
=> Make autodismiss workflow less sensitive

src/components/ScholarshipForm.jsx, src/components/SubmissionAlert.jsx
Fixes #597 
On laptop using firefox.
1. Go to https://s4us-pr-NUMBER.onrender.com/scholarships/new.
2. add new scholarship 
3. see submission alert that comes out at the bottom (should work the same as before)
=> refactoring of SubmissionAlert

src/App.jsx, src/pages/ListScholarships.jsx, src/pages/ListScholarships.test.jsx, src/pages/ViewScholarship.jsx, src/pages/ViewScholarship.test.jsx
This helps better distinguish the purposes of these components.
You can browse scholarships on Render and clicking one of them. Existing tests also use the renamed components.
=> Rename scholarships pages

src/components/FormikTextField.jsx, src/components/ScholarshipForm.jsx
Fixes #625. Refactored so it can make the `ScholarshipForm` easier to read.
laptop
1. Go to https://s4us-pr-627.onrender.com/scholarships/new.
2. TextFields should look as they did before
=> Refactor TextFields in ScholarshipForm

.github/workflows/validation.yml
Sometimes these checks don't run on stacked PRs, e.g. #622.
We'll test it on #622 once it's merged.
=> Run validation checks on all PR events

src/components/ScholarshipList.jsx
Currently there's no spacing between items in the scholarship list as warranted by our design. This is because there was a single grid item containing everything so no spacing was added between anything. 
Helps with #31
You can view the new changes on Render.
1. Go to https://s4us-pr-623.onrender.com/scholarships.
2. Notice how there's now spacing between list items
=> Fix ScholarshipList spacing between items

src/components/AmountTextField.jsx, src/components/DatePicker.jsx, src/components/DatePicker.test.jsx, src/components/FormikTextField.jsx, src/components/ScholarshipAmountField.jsx, src/components/ScholarshipAmountField.test.jsx, src/components/ScholarshipForm.jsx
Fixes #601
On laptop and mobile.
1. Go to https://s4us-pr-613.onrender.com/scholarships/new.
=> Form general section styling

src/pages/AddScholarship.jsx
Added support for new fields in the `requirements` section.
Also included `organization` and `tags`. 
on laptop using local host.
=> Requirements new field values added to Scholarship

src/components/Header.jsx
Helps separate concerns over the alerts that belong in the header. Part of the code #642 introduces.
Existing tests pass.
=> Refactor header alerts

src/components/Header.jsx, src/components/HeaderNavMenu.jsx
To create the AppBar in #642 we need to decouple the auth button in the header from the navigation links.
Existing tests still pass. Will test in the Render preview too.
1. Go to https://s4us-pr-646.onrender.com.
2. The header at the top should still look fine.
=> Move auth button from HeaderNavMenu to Header

src/components/Header.jsx
Our site was broken when you logged in because it could not find an IconButton. 
Localhost
2. Log in
3. website should not break
=> No IconButton bug fix in Header

package.json, public/index.html, public/manifest.json, src/App.jsx, src/pages/About.jsx, src/pages/AddScholarship.jsx, src/pages/Contact.jsx, src/pages/ListScholarships.jsx, src/pages/UserHome.jsx, src/pages/ViewScholarship.jsx, src/pages/ViewScholarship.test.jsx, tsconfig.json, yarn.lock
[React Helmet](https://github.com/nfl/react-helmet) does a better job at managing titles than the solution I had originally come up with. E.g., now our pages have a default title and there's a title template that wraps whatever title subcomponents decide to have later on.
Fixes #208 
Locally in browser by hovering over tab name.
2. Hover over the tab in your browser to see the rendered title.
3. Click around and see how it changes dynamically based on the component rendered.
=> Use react helmet and update titles/app names

src/components/ScholarshipForm.jsx
There was a weird bug with the buttons so I fixed it and changed how the buttons are rendered. 
The bug allowed submission of the form when clicking on the `NEXT` button. Adding a `key` attribute to the button fixed it, per this [Formik issue](https://github.com/formium/formik/issues/2004). 
Laptop using local host
1. Go to https://s4us-pr-635.onrender.com/scholarships/new.
=> scholarship form Next and Submit button refactored

public/index.html, src/components/Header.jsx, src/components/HeaderNavMenu.jsx
Helps with the creation of the AppBar in #642.
Existing header tests pass.
1. Go to https://s4us-pr-647.onrender.com.
2. Interact with the tabs in the top.
=> Use tabs for Header nav menu

src/components/Header.jsx, src/pages/About.jsx, src/pages/AddScholarship.jsx, src/pages/Contact.jsx, src/pages/ListScholarships.jsx, src/pages/PublicHome.jsx, src/pages/UserHome.jsx, src/pages/ViewScholarship.jsx
Fixes #518.
Locally.
1. Click on Render link below and click around.
2. Especially checkout the **Contact** page.
=> Use Typography components wherever possible

src/components/FormikAutocomplete.jsx, src/components/FormikMultiSelect.jsx, src/components/FormikTextField.jsx, src/components/ScholarshipForm.jsx, src/models/Scholarships.test.ts, src/models/Scholarships.ts, src/pages/AddScholarship.jsx, src/pages/EditScholarship.jsx, src/types/ScholarshipData.ts
- Do not assume a particular path for Formik input types
- Initialize new scholarships with required field defaults
- Support unset optional fields in the form.
Helps isolate better the responsibilities of the page component vs. the form component. 
Locally
1. Go to https://s4us-pr-717.onrender.com.
1. Log in.
1. Try adding or editing a scholarship you own.
=> ScholarshipForm improvements

src/firestore.rules.test.js
Also cleaned it up a bit since most tests are single statements.
Helps with #718, particularly the issue around
They are tests.
=> Add missing firestore rule test

.vscode/launch.json
Adds debugging targets everyone can use.
Locally.
=> Add VS Code Chrome and test debugging targets

src/components/FormikMultiSelect.jsx
Fixes `multiSelect` placeholder not matching color with other placeholders (when disabled) 
locally
1. Go to https://s4us-pr-725.onrender.com/scholarships/new.
2. go to requirements section
3. click 'NO REQUIREMENTS' checkbox
4. placeholder color for all selects should be the same
=> placeholder disabled color fix

src/components/ScholarshipDetailCard.jsx
Fixes #723 and #584. 
Shows schools as part of the requirements section. 
Locally
1. Go to https://s4us-pr-NUMBER.onrender.com/scholarships.
2. choose a scholarship
3. tags displayed properly, (if applicable)
4. schools requirement shown
5. newline in description shown properly
=> ScholarshipDetailCard bug fixes

src/components/FilterBar.jsx, src/components/FormikMultiSelect.jsx, src/components/GradeLevelFilter.jsx, src/lib/QueryParams.js, src/pages/ListScholarships.jsx, src/types/GradeLevel.ts
Fixes #275
prunes duplicate grade values, and removes grade values that are not represented by the `GradeLevel` enum.
local
1. Go to https://s4us-pr-726.onrender.com/scholarships?expShowGradeFilter=1.
2. click some grades and watch the parameters change with it
3. you can also provide some grades in the url and see the changes reflected in the filter
4. try inputting some invalid grade values, should prune those values
=> Grade filter param support

src/components/AboutCard.jsx, src/components/AmountTextField.jsx, src/components/FilterBar.jsx, src/components/FilterDropdown.jsx, src/components/GradeLevelFilter.jsx, src/components/HeaderNavMenu.jsx, src/components/HomeSection.jsx, src/components/ProfileDropdown.jsx, src/components/ProtectedRoute.jsx, src/components/ScholarshipAmountField.jsx, src/components/ScholarshipList.jsx, src/pages/Home.jsx, src/pages/UserHome.jsx
Helps with #636. Basically, we should use `sx` property wherever styling applies to only one element. But if we want a styling to apply to multiple elements then we should used the [`styled`](https://mui.com/system/styled/#main-content) API.
Additional context: https://mui.com/guides/migration-v4/#migrate-from-jss
Existing tests should provide decent coverage. 🤷
=> Migrate some JSS to SX props

src/components/ScholarshipListCard.jsx
Fixes #748 
Also made changes to use `sx` props
locally
1. Go to https://s4us-pr-749.onrender.com/scholarships.
2. Tags should now render properly
=> ScholarshipListcard tags bug

src/components/ScholarshipDetailCard.jsx, src/components/ScholarshipListCard.jsx, src/types/ScholarshipAmount.test.ts, src/types/ScholarshipAmount.ts
Style fixes to make the scholarship detail card & scholarship list card look like the Figma design. 
Locally
1. Go to https://s4us-pr-788.onrender.com/scholarships.
2. click on a scholarship
=> ScholarshipDetailCard & ListCard redesign

firestore.rules, src/components/ScholarshipDetailCard.jsx, src/firestore.rules.test.js, src/pages/EditScholarship.jsx
Fixes #812 
Added unit tests for the firestore rules.
Otherwise manually tested (though this should really be added to the tests):
1. Before granting myself the `admin` role I tried editing a scholarship someone else owns. I made sure:
2. Then I granted myself the `admin` role and made sure I was able to edit the same scholarship.
1. Go to https://s4us-pr-813.onrender.com.
2. See if you can access the edit scholarship form of a scholarship you don't own.
3. If you have `admin` access you should be able to. Otherwise you shouldn't be able to.
=> Support editing scholarships for admins

src/components/ProfileDropdown.jsx
Fixes #819 
Locally.
1. Go to Render preview URL below.
2. Login
3. Click avatar on top right.
4. Spacing should be fixed.
=> Fix profile dropdown spacing issue

src/lib/FirebaseProvider.tsx
Fixes #213 
This Render preview for this PR should be using the staging project.
=> Add staging project config for Render previews

src/components/AmountFilter.jsx, src/components/DatePicker.jsx, src/components/Footer.jsx, src/components/FormikAutocomplete.jsx, src/components/FormikMultiSelect.jsx, src/components/FormikTextField.jsx, src/components/Header.jsx, src/components/ScholarshipAmountField.jsx, src/components/ScholarshipForm.jsx, src/components/ShareDialog.jsx
Fixes #636. Last of the migration PRs. Changed some things slightly but should still work.
Existing tests pass. Also manually checked to make sure things still looked ok.
1. Go to render preview URL below.
2. Click around and make sure nothing's broken.
=> Migrate away from JSS

src/components/ScholarshipDetailCard.jsx, src/components/ScholarshipListCard.jsx, src/components/ShareDialog.jsx, src/theme.js
=> Theme update

src/components/Header.jsx, src/components/ProfileDropdown.jsx
Fixes #856
Locally
1. Go to https://s4us-pr-857.onrender.com.
2. Try logging in and out.
3. Hopefully the menu doesn't appear in the top left anymore and at a wrong time?
=> Fix menu anchor issues

src/components/ScholarshipForm.jsx, src/types/options.ts
This allows us to do more sophisticated analysis with states and schools, especially with what we plan to do for #858.
Locally.
1. Go to PR preview below.
2. Try adding a scholarship and verify that the state and school dropdowns are the same as before.
=> Make states and schools lists of typed interfaces

.github/pull_request_template.md
Trying to make the PR template more streamlined.
=> Shorten/simplify PR template

src/components/ScholarshipList.jsx
The Grid is one-dimensional. Stack is a new way to do 1-D grids in MUIv5.
=> Make ScholarshipList use Stack instead of Grid

src/components/ScholarshipCard.jsx
Must've happened when I did the refactors.
=> Fix minor tag issues

package.json, src/App.jsx, src/components/Header.jsx, src/components/HeaderNavMenu.jsx, src/components/LoginDialog.jsx, src/components/LookingForScholarshipsBanner.jsx, src/components/ProtectedRoute.jsx, src/components/ScholarshipCard.jsx, src/components/ScholarshipForm.jsx, src/components/ShareDialog.jsx, src/pages/EditScholarship.jsx, src/pages/ListScholarships.jsx, src/pages/ListScholarships.test.jsx, src/pages/UserHome.jsx, src/pages/ViewScholarship.jsx, src/pages/ViewScholarship.test.jsx, yarn.lock
Also changed the way some alerts get dismissed since we can use [useNavigationType](https://reactrouter.com/docs/en/v6/api#usenavigationtype) to determine whether we arrived there from a push (as opposed to popping when going back).
Fixes #803 
1. Check for any broken paths. Our tests and my manual tests may have missed something.
=> Upgrade React Router to v6

src/App.jsx, src/components/Header.jsx, src/components/LoginDialog.jsx, src/components/ProtectedRoute.jsx, src/components/ScholarshipCard.jsx, src/components/ScholarshipsMadeSimple.jsx, src/lib/experiments.ts, src/pages/About.jsx, src/pages/AddScholarship.jsx, src/pages/Contact.jsx, src/pages/ListScholarships.jsx, src/pages/UserHome.jsx, src/theme.js
Better aligns with design I think.
1. Click around.
2. Compare with dreamscholars.org in a separate tab or side by side.
=> Minor styling improvements around app bar and presentation

src/pages/ListScholarships.jsx
#803 introduced this bug when I was trying to convert history.push/replace calls to navigate. This was causing the filters to not work. We should really add tests for them. :P
1. Go to Scholarships
2. Try the filters and make sure they work.
=> Fix navigate bug introduced by react-router upgrade

src/App.jsx, src/components/FilterPanel.jsx, src/pages/ListScholarships.jsx
This isn't the final version of it but it should be enough to unblock filter panel styling work.
Unblocks styling work for #872 as well as prep for #31. 
1. Go to the Scholarships page.
2. Notice panel on the left.
=> Basic filter panel for large screens

package.json, src/App.jsx, src/components/FilterBar.jsx, src/components/FilterPanel.jsx, src/lib/QueryParams.js, src/lib/useQueryParams.test.tsx, src/lib/useQueryParams.ts, src/pages/ListScholarships.jsx, yarn.lock
Fixes #532 and #878 by providing a custom hook better suited for our needs. 
1. Go to Scholarships page
2. Try setting filters and putting bad values in the URL for known keys.
=> Implement useQueryParams hook

src/components/ScholarshipForm.jsx, src/models/ScholarshipsContext.tsx, src/pages/EditScholarship.jsx, src/pages/ViewScholarship.jsx, src/pages/ViewScholarship.test.jsx
Fixes bugs introduced by #890 to fix #639. Essentially, use the context wherever possible and provide a way to clear all scholarships or remove/update a scholarship from the cache.
1. Try editing a scholarship and going back. The prior pages should reflect the updated details.
2. Try adding a scholarship and going back. The list should refresh.
3. Try deleting a scholarship and going back. The list should no longer have the deleted scholarship.
=> Use ScholarshipsContext everywhere

src/components/ScholarshipCard.tsx
Just noticed the condition was flipped. We really need a test for this :P
1. See list cards and click on them. Make sure they're detailed when you expect them to be.
=> Fix bug showing full description in list/view pages

src/pages/ListScholarships.jsx
#889 forgot to update the ref so that scroll restoration works.
=> Fix scroll restoration

src/App.jsx, src/components/Header.jsx, src/pages/ListScholarships.jsx
Fixes #903. The app bar at the top takes up screen real estate. 
1. Go to the scholarships page.
2. Scroll up and down.
3. Notice the App bar disappears and filter bar slides in.
4. Try in both mobile and desktop.
=> Hide app bar and slide in filter bar on scroll

src/lib/lint.test.ts, src/lib/lint.ts
=> Detect graduating senior from high school in linter

src/components/ScholarshipList.jsx, src/components/ScholarshipList.test.jsx, src/lib/useOnScreen.ts, src/pages/ListScholarships.test.jsx
Fixes #936
1. Go to the Scholarships page.
2. Try scrolling to the bottom.
3. More results should automatically load.
=> Auto load more scholarships

src/components/ScholarshipCard.tsx, src/validation/ValidationSchema.js
Some scholarships need this. E.g. https://dreamscholars.org/scholarships/3lJrr5oAHxlLlNuchFxn
1. Try creating or editing a scholarship with GPA to 2 decimal places.
=> Support GPA to two decimal places

src/components/FormikTextField.jsx
Fixes a bug where the gpa field was not being cleared when the `no requirements` checkbox was checked.
2. add scholarship & add a gpa requirement
3. click the `no requirements` checkbox
4. gpa field should clear
=> Gpa bug when clearing requirements

src/components/ScholarshipCard.tsx, src/components/ScholarshipForm.jsx, src/lib/lint.ts
Fixes #932 
2. Add new scholarship & put some requirements in the description field
3. should see an alert when in the requirements section 
4. click autofill button
5. Edit a scholarship with lint issues & click autofill button
=> Autocomplete form fields

src/components/HeaderNavMenu.test.jsx
I ran `yarn test` and the tests passed!
=> add tests for HeaderNavMenu component

src/lib/useOnScreen.ts, src/pages/ListScholarships.jsx
Fixes minor bugs when resizing side panel. The side panel wasn't resizing properly when the page loaded more scholarships. Additionally, it allowed you to horizontally scroll within the side panel.
2. go to scholarships page
3. load more scholarships
=> Side Panel bug fixes

src/components/ScholarshipCard.tsx, src/pages/ViewScholarship.test.jsx
Sorts requirements in the detail card. This includes the grades, ethnicites, schools & majors
2. Add new scholarship with requirements
3. view preview & notice how requirements are now sorted
=> Sorting requirements in detail card

src/App.jsx, src/App.test.jsx, src/ScrollToTop.jsx
Fixes #954 
2. scroll in any page and go to another page
3. new page should start from the top
=> scroll to top

src/lib/lint.test.ts, src/lib/lint.ts
Fixes false detections like the one due to a ZIP code at https://dreamscholars.org/scholarships/cJycxmCPgBOz4ikaxw86
=> Detect school periods more properly

public/index.html, src/components/LoginDialog.jsx, src/i18n/translations/english.json, src/i18n/translations/spanish.json
Fixes #320 & adds spanish translations. 
2. click login 
3. font should not longer change
4. change language & click login btn
=> Login dialog spanish translations & font change bug fix

src/components/FormikAutocomplete.jsx, src/types/options.test.ts, src/types/options.ts
- Deduplicated schools, which fixes a weird issue we had with irrelevant results showing up.
- Added matching for acronyms for autocomplete
Fixes #939 as well as an issue we had with irrelevant options sometimes showing up.
1. Try creating or editing a scholarship
1. Add school requirements.
2. No duplicate entries nor irrelevant entries should show up.
3. Additionally, if you type out an acronym (e.g. `UCI`) relevant entries matching the acronym should show up.
4. Same should work for other autocompletes, e.g. `CS` for majors.
=> Improve schools autocomplete

src/components/FormikAutocomplete.jsx, src/components/ScholarshipForm.jsx, src/types/options.ts
Adds tag support. 
2. add new scholarship with tags
=> tags support

src/components/LoginDialog.jsx, src/components/ScholarshipCard.tsx, src/components/ShareDialog.jsx, src/lib/FirebaseProvider.tsx, src/lib/testing.ts, src/pages/ListScholarships.jsx
Fixes #674. Added most relevant provided events. We might want to add other types of events later.
1. Try logging in, searching, sharing, viewing scholarships, etc.
1. Eventually the events should appear (within a day) on the [staging project analytics dashboard](https://console.firebase.google.com/u/0/project/dreamerscholars-staging/analytics/)
=> Add analytics to the site

src/components/FilterBar.jsx, src/components/FilterPanel.jsx, src/components/MajorFilter.jsx, src/pages/ListScholarships.jsx
Fixes #919 
2. go to scolarships page
3. apply and remove filters
=> Filter chips above results

src/components/HomeSection.jsx, src/theme.js
Fixes font size on mobile screens  
2. re-size window and make sure text changes size
=> font fix on mobile screen

.github/ISSUE_TEMPLATE/bug_report.yaml
Minor tweaks to bug report issue form template.
https://github.com/beyondhb1079/s4us/blob/josueetcom-patch-9/.github/ISSUE_TEMPLATE/bug_report.yaml
=> Tweak bug_report.yaml

.github/ISSUE_TEMPLATE/bug_report.yaml, .github/ISSUE_TEMPLATE/feature_request.yaml
This filters out closed issues.
1.
=> Update Issue form "search" links

src/components/LoginDialog.tsx, src/components/ShareDialog.tsx
=> Migrate Dialog components to TypeScript

src/components/ScholarshipCard.tsx, src/components/ScholarshipForm.jsx, src/pages/AddScholarship.jsx, src/pages/EditScholarship.jsx
Fixes #1045. Fixes #985
2. add / edit a scholarship
4. notice the detail card on the right when viewing through a bigger screen
5. try viewing on mobile
=> Show scholarship card on right side of scholarship form

src/App.jsx, src/components/Footer.jsx, src/components/Header.jsx, src/i18n/translations/english.json, src/i18n/translations/spanish.json, src/lib/mail.ts, src/pages/Privacy.tsx, src/pages/Terms.tsx
- Removed under construction banner
- Updated email alias
- Added privacy and terms page
Fixes #1048. Fixes #1047. 
- Privacy page: https://s4us-pr-1049.onrender.com/privacy
- Terms page: https://s4us-pr-1049.onrender.com/terms
=> Prepare website for beta launch + privacy/terms pages

src/components/ProfileDropdown.jsx
Fixes #987 
1. Log in
2. Click your profile pic at the top right
3. Click **Dashboard**.
=> Add Dashboard button to profile dropdown component

src/lib/useQueryParams.ts
Fixes scholarships filter not working
2. go to scholarships page
3. apply some filters
=> Filters bug fix

src/components/ScholarshipCard.tsx, src/components/ShowMoreScholarships.jsx, src/pages/ViewScholarship.jsx, src/pages/ViewScholarship.test.jsx
Fixes #1052 and also styling changes that weren't addressed in #965.
1. Find a scholarship and click on it.
2. At the bottom the area should be better styled.
3. Refresh the page and there should still be scholarships there.
=> Fix "more scholarships" behavior and styling

package.json, src/components/AboutCard.test.tsx, src/components/AboutCard.tsx, src/pages/About.tsx, yarn.lock
=> Typescript Migration: About page and components

src/App.jsx, src/components/Header.tsx, src/components/LoginDialog.tsx, src/components/ProfileDropdown.jsx, src/lib/FirebaseProvider.tsx, src/lib/useAuth.tsx, src/pages/Home.tsx
- Lazy load modules that take a while to load (e.g. Firebase, the Firebase auth UI)
- Lazy load pages since the user only needs to see initial page
This lets the Header of the page and a loading progress indicator get seen much more quickly. Also
requested bytes dropped from [2.6 MiB](https://googlechrome.github.io/lighthouse/treemap/?gzip=1#H4sIAAAAAAAAE7V9C2/cyLXmXzGMxWJ3Ma1uvskBLm5k2R77xhorliazj5sV2M1qNW022SHZlpUg/32riuwWv+I5RSrBIsBElurUi6fO86tTf39d7OrXP//9dS3+ehRNK7Lf6uL1z693bXtofl4us1qk+2azq4q0bi6q+mH5+qfX27xMixnt0mOWt43qvdnU+aFdtLUQ+/SwyNI2Vb/OM9kF9befXrd5Wwj511v911d33V9fve3+momOKq9K2ea3RmSvtlX9qu/jVXo4yEbNpqplF+WxKPp/vM2bQ5E+XVeZ6jovJc0+bfPvQnfZpnmhZ9s+HdTfjRmVkkr++f/8/XWZ7sXU2mvRVMd6I948tYrKDdzkHz/NIG1aOaHN8muzDC78lZ+EWze72OyO5beLr824X8ddeT+9PpZHuQX9r1YvHCe+cDexn7qBbRwvmjPM4+PjxUNV …
=> Speed up Landing home page performance

.github/workflows/audit.yml, .github/workflows/ci.yml
Our CI deploy was failing due to using old Node.js versions. It doesn't help that the entire pipeline fails because of audit checks always failing:
https://github.com/beyondhb1079/s4us/actions/workflows/ci.yml
Upgraded node version and separated audit check so it's easier to tell when CI breaks.
=> Fix CI pipeline

.github/workflows/ci.yml
=> _Really_ fix CI pipeline this time

src/components/ScholarshipCard.test.tsx, src/components/ScholarshipCard.tsx, src/pages/ViewScholarship.test.jsx
Additional event for when the user interacts with our site. I think this is an important metric because them going to the scholarship website is basically our target goal.
The **Apply** button still works but I'm hoping to see the events I created in our staging app eventually.
=> Log Analytics event when user clicks Apply button

src/components/ProfileDropdown.jsx
Apparently when I did the migration to Firebase Web SDK v9 I messed up on the signOut part. It takes in an Auth object, like how it's shown [here](https://firebase.google.com/docs/auth/web/password-auth#next_steps).
=> Fix logout bug caused by Firebase Web SDK upgrade

src/components/Header.tsx, src/components/ProfileDropdown.jsx
This restructure helps with #1102 as the ProfileMenu (along with the Avatar) only gets rendered if you're logged in.
Not much new visually, perhaps a _very very_ slight performance improvement. At minimum it'll end up reducing the JS files loaded initially just a bit.
=> Better encapsulate ProfileDropdown

src/components/Header.tsx, src/components/ProfileMenu.tsx
=> TypeScript migration: ProfileDropdown -> ProfileMenu

src/components/Header.tsx, src/components/TranslationMenu.tsx
Was noticing the logic around this is separated and should probably be grouped. Moved out of Header to declutter it.
1. See updated icon!
=> Refactor Translation Menu and update icon

src/components/Header.tsx
This was one of the last steps for #636. See https://mui.com/material-ui/guides/migration-v4/#hidden for details.
1. Check that the header works as expected in mobile/desktop.
=> Migrate away from <Hidden>

src/components/MinAmountFilter.tsx
=> MinAmountFilter typescript conversion

src/components/ProtectedRoute.tsx
=> Protected route typescript migration 

firestore.rules, src/firestore.rules.test.ts
Some test simplification I did while working on #1156. That one still needs some more changes I have to continue investigating. Rather than wait and have one giant PR I think it's better to separate this one as its own PR.
=> Simplify firestore.rules.test.ts

.github/workflows/validation.yml, README.md, package.json, src/App.test.tsx, src/components/Header.test.tsx, src/components/Header.tsx, src/lib/FirebaseProvider.tsx, src/lib/testing.ts, src/models/Scholarships.ts, src/models/base/FirestoreCollection.test.ts, src/models/base/FirestoreModel.test.ts, src/pages/ListScholarships.tsx, src/serviceWorker.ts
Fixes #922. Though we need to seriously improve coverage.
1. Check out the logs from the **Validation / test** check below.
=> Add coverage thresholds

src/components/FilterBar.tsx, src/components/FilterPanel.tsx, src/components/Footer.tsx, src/components/LookingForScholarshipsBanner.tsx, src/components/ShowMoreScholarships.tsx
Fixes #1003. Fixes #1004. Fixes #1014.
=> TypeScript migration: Filter bar and panel, and two more components

public/locales/en/filters.json, public/locales/es/filters.json, src/components/CustomAutocomplete.tsx, src/components/FilterPanel.test.tsx, src/components/FilterPanel.tsx, src/components/ScholarshipList.tsx, src/lib/useQueryParams.test.tsx, src/lib/useQueryParams.ts, src/models/Scholarships.test.ts, src/models/Scholarships.ts, src/pages/ListScholarships.test.tsx, src/pages/ListScholarships.tsx
Fixes #992 
2. go to scholarships page 
3. filter by ethnicity
=> Ethnicity Filter

src/components/GradeLevelFilter.tsx, src/types/GradeLevel.ts
Fixes #991 
2. go to scholarships page
3. view grade filters and check a parent checkbox
4. try selecting/de-selecting group by clicking on parent
=> Grade filter groups

public/index.html
=> Fix meta description typo

.vscode/settings.json, public/index.html, public/locales/en/about.json, public/locales/en/home.json, public/locales/es/common.json, public/locales/es/home.json, src/pages/About.tsx, src/pages/Privacy.tsx, src/pages/Terms.tsx
Helps with #1222 as less typos should make the site easier to find and the titles should more clearly describe the purpose of each page.
1. See typos fixed.
=> Fix typos and titles

src/components/ScholarshipList.tsx, src/components/ShowMoreScholarships.tsx, src/lib/useQueryParams.test.tsx, src/lib/useQueryParams.ts, src/models/Scholarships.test.ts, src/models/Scholarships.ts, src/pages/Dashboard.tsx, src/pages/ListScholarships.tsx
Helps with updating scholarships so that we can provide a link to each other that shows _all_ scholarships in the database regardless of whether they're expired or not.
1. Visit https://s4us-pr-1262.onrender.com/scholarships
2. Visit https://s4us-pr-1262.onrender.com/scholarships?showExpired=true
3. The latter should show any expired scholarships.
=> Support showing expired scholarships
