beyondhb1079/s4us

firebase.json
https://dreamerscholars.web.app/scholarships returns a 404. It turns out that rewriting to `/` is not the same as rewriting to `index.html`
=> Fix Firebase rewrites to route to index.html

.github/workflows/audit.yml, .github/workflows/validate.yml
It's a bit frustrating to see an audit check fail but no fix available when you haven't changed the dependencies. Now that we have [Dependabot updates](https://github.com/beyondhb1079/s4us/network/updates) set up, we can rely on it to create PRs to update dependencies. So instead let's leave this check for commits to `main` and PRs that touch `yarn.lock`
=> Run audit check only when yarn.lock is modified and on merges to main

.github/workflows/ossar-analysis.yml
Otherwise it ends up running on any push and on any pull request event, which leads to duplicate runs when updating a pull request and unnecessary runs for feature branches not yet ready for review.
=> Run ossar-analysis.yml on PRs and pushes to main only

src/components/LoginButton.jsx
There were technically two bugs here:
- on every render we were registering a listener on auth state changed
- if/when this component unmounts each listener would _still_ listen for auth changes and trying to set state of the unmounted component
Using [`useEffect`](https://en.reactjs.org/docs/hooks-effect.html) here allows us to register a single listener and return a cleanup function that unregisters the listener when the component unmounts.
=> Update LoginButton.jsx to use React effect hooks

package.json, yarn.lock
This'll update the node-forge dependencies rely on so that we stop getting the Audit failure.
=> fix audit issues (hopefully)

firebase.json, package.json, src/App.jsx, src/components/Header.test.jsx, src/config/FirebaseConfig.jsx, src/lib/FirebaseProvider.tsx
- Create a [Context](https://en.reactjs.org/docs/context.html) that initializes the Firebase app once.
- In the Firebase context provider, connect to the Firestore emulator instead when in development.
- Make `yarn start` surround `react-scripts start` with setup of Firebase emulators and the UI (located at http://localhost:4000 when running `yarn start`)
Fixes #212, which solves two issues:
- Touching Firestore production data while developing locally iteratively
- Initializing Firebase app just once. The way we had it before it could technically be initialized again if the `<App>` component were re-rendered.
Locally it runs the Firestore emulator, which shows no scholarship data. But on the [Render preview](https://s4us-pr-215.onrender.com/scholarships) it shows the production data.
=> Create Firebase context provider that uses emulators on local development

.github/workflows/dependabot-autoapprove.yml
Context: 
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
This is why the **Dependabot Automerge** checks are failing. I've simplified the logic to just auto approve dependabot PRs. They won't be able to go in without passing the checks first anyways.
=> Autoapprove all dependabot PRs

src/lib/FirebaseProvider.tsx
As a developer any Firestore changes you make in the Emulator UI doesn't get reflected in the React app. This is because the UI is emulating for the `dreamscholars` project while the React app is trying to talk to `dreamscholars-dev`.
I've tried it locally.
=> Set dev Firebase config to match default project

.github/dependabot.yml
So we get less dependabot PRs but still get updates frequently enough :)
=> Decrease dependency updates to once a month

.gitignore, package.json, src/components/ScholarshipList.jsx, src/pages/ScholarshipDetails.jsx, src/pages/ScholarshipDetails.test.jsx, src/pages/Scholarships.jsx, src/types/ScholarshipAmount.ts, yarn.lock
- Pass scholarship data from results page to detail page via [location.state](https://reactrouter.com/web/api/location)
- In detail page, only fetch data if needed
- In detail page, clear location state so that refreshing the page works (we might at some point want to remove this but for now it's unintuitive if the data doesn't update on refresh).
Additionally:
- Persist Firestore emulator data across `yarn start` sessions. This'll prevent us from having to create scholarships each time.
- Fix warnings `yarn test` was complaining about.
- Silence lint warnings.
Fixes #204. This reduces having to make another Firestore call in the detail view when we already have that data in the list view. There shouldn't be a need to re-fetch data we already have.
I added a new test that makes sure the …
=> Pass scholarship state between list and detail pages

src/models/Scholarships.test.ts, src/models/Scholarships.ts, src/types/ScholarshipAmount.test.ts, src/types/ScholarshipAmount.ts
This allows sorting by min/max make sense regardless of amount type (as long as scholarship award amounts don't surpass $1 billion).
Fixes #344 
I added tests.
=> Make ScholarshipAmount min/maxes sortable regardless of type

src/models/base/FirestoreModel.test.ts
This is a temporary fix for #356. For some reason it sometimes fails as if non-open firestore rules were set. This change allows the test to pass in either case.
=> Temp fix to nondeterministic test issue

.github/workflows/validate.yml
Our style job only relies on prettier so rather than install everything from package.json let's just install prettier alone.
If you look at the [Validation actions](https://github.com/beyondhb1079/s4us/actions?query=workflow%3AValidation) the `style` validation job is usually the fastest at around `1m10s` or so. But... this can be made faster by ignoring all other dependencies. 
Look at how fast `style` jobs have run in the [checks](371/checks) for this PR for each commit. Blazing fast under 10 seconds!
=> Optimize style validation job by only installing Prettier

.github/workflows/validate.yml
If you look at old validation workflows like [this one](https://github.com/beyondhb1079/s4us/actions/runs/542566911) you'll see that the **build**, **lint**, and **test** checks all spend around 1 minute dealing with the yarn cache and installing dependencies.
Since our `yarn.lock` file tells us exactly which dependencies to use, if we instead cache `node_modules` and skip the installation step on cache hits, this'll allow us to:
1. Speed up the caching step because node_modules is more than 50% smaller than the yarn cache directory.
2. Skip installation steps entirely when we get a cache hit.
In total, this speeds up each of these checks by about 50 seconds!
E.g. [before](https://github.com/beyondhb1079/s4us/actions/runs/542566911) vs …
=> Make validation checks cache node_modules instead

package.json
Now that #374 has sped up validation check tests significantly I think we can remove this overhead from pushing. We should really be pushing often and the 1.5-2.5 minutes this takes discourages you from pushing often. I had introduced it to catch things sooner but it's probably causing more toil than helping, especially now that it takes less than a minute to get feedback form the validation check.
Note: I've kept linting in the pre-push as that only takes around 30 seconds and it'll catch some things the build check will complain about.
=> Remove testing from pre-push hook

firestore.indexes.json
Our CI workflows have been failing ever since I submitted #409:
https://github.com/beyondhb1079/s4us/actions/workflows/deploy.yml
I compared with the output of `firebase firestore:indexes` and found that we sillily wrote `amount.deadline` instead of `deadline`.
=> fix firestore indexes deadline field typo

.github/workflows/dependabot-autoapprove.yml
This action has been failing lately:
https://github.com/beyondhb1079/s4us/actions/workflows/dependabot-autoapprove.yml
I think it might be because we're using an older version of github-script.
=> Update autoapprove dependabot action to use github-script@v3

README.md, package.json, src/lib/FirebaseProvider.tsx, src/models/Scholarships.test.ts, src/models/Scholarships.ts, src/models/base/FirestoreCollection.test.ts, src/models/base/FirestoreCollection.ts, src/models/base/FirestoreModel.test.ts, src/models/base/FirestoreModel.ts, tsconfig.json, yarn.lock
Updated the versions of firebase dependencies as well. 
Fixes #214. This allows easier local auth testing (e.g. different roles and different accounts).
When running `yarn start`, the login experience goes to http://localhost:9099 and it lets you create testing accounts as needed. Also, when the emulator is running you can see the accounts you created at http://localhost:4000/auth
1. Checkout this branch
2. `yarn start`
3. Try logging in
=> Connect to the Auth emulator on local development

src/pages/UserHome.jsx
It does not make sense as a user that has added a scholarship to have the "no scholarships component" appear as they should only see their list of scholarships added.
Users that have not added a scholarship will remain the same as they will be viewing the "no scholarships component".
Fixes #468 
Used the emulator to create a user that has a scholarship added and refreshed the page to ensure the "no scholarships component" does appear after loading scholarships. The list of added scholarships do appear and also removed the text that said "no more results".
Then I created another user in the emulator that does not have any scholarships added and the loading happens and after the "no scholarships component" does appear. 
1. Go to https://s4us-pr-486.onrender.com.
2. Login
3. There can be two …
=> fixed the glitch user home page flickers no scholarships when loading

.github/workflows/approvals.yml, .github/workflows/dependabot.yml
I finally understand why `dependabot` triggered checks like https://github.com/beyondhb1079/s4us/pull/534/checks?check_run_id=2969026240 keep failing.
For security reasons, the default [permissions](https://docs.github.com/en/actions/reference/authentication-in-a-workflow#permissions-for-the-github_token) on the GitHub token is read-only for Dependabot pull requests so we have to use the `pull_request_target` event instead.
Additional details in dependabot/dependabot-core#3253.
=> Finally fix autoapprove dependabot workflow

.github/workflows/ci.yml
It looks like yarn build now has some dependencies on our dev dependencies :/
https://github.com/beyondhb1079/s4us/runs/3034499921
=> Fix CI pipeline

src/lib/FirebaseProvider.tsx
Just tried it out against the live site. When you try logging in it no longer displays the firebaseapp.com domain.
=> Set the auth domain to dreamscholars.org

.github/workflows/approvals.yml
It's annoying to see clean merges dismiss approvals. This checks to see whether there have only been clean merges since the last approved commit and prevents dismissal.
Manually tried some of the commands in the terminal. Been running it against this PR. Will wait to merge until it's merged lots of changes from main before merging this one to make sure this actually works.
=> Don't dismiss approval on clean merges

src/pages/UserHome.jsx
If you log in to https://dreamscholars.org/ it's currently broken because of a missing import.
=> Fix UserHome missing import bug

scripts/emulators_exec.sh
If for some reason the lock file exists but the emulators aren't running you'll run into some issues. This'll instead check if there's already a process running on the Firestore emulator port and print the PID if so.
Locally.
=> Fix emulator exec script to detect running process instead

src/lib/lint.test.ts, src/lib/lint.ts, src/models/Scholarships.test.ts, src/types/Ethnicity.ts, src/types/GradeLevel.ts
Also tidied up GradeLevel and Ethnicity a bit so that:
- 5th year option is commented out (couldn't find this in our scholarship sheet)
- GradeLevel now has a variable for certain school levels
- GradeLevel string representation better represent the strings I found in our scholarship sheet.
- Each have correctly typed `keys()` and `values()` methods.
Helps with #858.
1. Try looking for creating a scholarship with grade level requirements.
1. Look for errors on the card.
=> Add lint check for missing grade level requirements

src/lib/lint.test.ts, src/lib/lint.ts
Fixes #858 
1. Try creating a scholarship with a conflicting deadline as the description or containing a single line descriptions with ` -` items.
2. Look for errors on the card.
=> Add lint checks for deadline and bullet points in single line descriptions

src/App.jsx, src/components/ScholarshipCard.jsx, src/components/ShareDialog.jsx
It's a bit wonky how this was used (relying on history state) and how a lot of the sharing logic is outside of it. I've made changes so that now:
- It's fully controlled by the parent component
- The ShareDialog encapsulates handling native device sharing  
1. Try sharing a scholarship
=> Make ShareDialog encapsulate sharing

src/components/Header.jsx, src/i18n/translations/english.json, src/i18n/translations/spanish.json
Our "Website under construction" alert is pretty tall and wordy so it ends up taking up valuable screen height on small screens in both landscape and portrait mode (sample below is iPhone 5 SE):
This change reduces that by removing the title (which is already redundant with the color/icon) and shortening the message.
1. Notice the thinner alert at the top compare to the one currently live at dreamscholars.org.
=> Shorten under construction alert

src/lib/lint.test.ts, src/lib/lint.ts
Addresses a slight bug introduced by #866 where amount strings with `,` in it are ignored:
1. Look for or create a scholarship with amount `N` where `N >= 1000` but has `,` in the amount value in the description.
2. Ensure there are no lint errors about it.
Lint error for amount is now gone:
=> Fix comma issue when linting amounts

src/lib/lint.test.ts, src/lib/lint.ts
Helps with #931 .
1. Look for or add a scholarship with a word in it that contains a major substring (e.g. `educational` for `education`)
2. Ensure it doesn't detect it as a missing major requirement.
=> Fix lint issue around substring matches for majors

src/lib/lint.test.ts, src/lib/lint.ts, src/types/options.ts
- Better detect some grade levels.
- Reduce noise around words like "history" and "education".
- Detect school if site and acronym present.
These were some of the improvements from the phase 2 update note doc.
You can try the edge cases from the unit tests out! They're not perfect by any means but it should reduce some noise and improve some things.
=> Lint improvements around grade level, major, and school

src/components/MajorFilter.jsx
Fixes bug that allows you to keep selecting majors even when the limit is reached.
2. go to scholarships page
3. reach limit of majors filter
=> Major filter exceed limit bug fix

src/components/ScholarshipForm.jsx
Currently you can only filter options by state abbreviations. This supports filtering by both since `State.toString()` contains both the state name and the state abbreviation.
1. Try creating/editing a scholarship
2. Try filtering a state by its abbreviation or name (e.g. `ME` and `Maine`)
3. Ensure the state you're looking for shows up
=> Support filtering state options by full name

src/components/ScholarshipForm.jsx
Fixes #1053 
1. Either add or edit a scholarship
2. Try enter a website value without the `http://` or `https://` prefix.
3. Click away
4. Notice how `https://` is automatically prepended.
=> Automatically add missing http prefix to website in scholarship form

src/components/ScholarshipCard.test.tsx, src/components/ScholarshipCard.tsx
Fixes #1091, which was a bug introduced by a one-liner change in #1046 🤦 . Lint issues couldn't be seen from the dashboard and any user could see lint issues regardless of permissions as long as they clicked on a scholarship.
Decided to add exhaustive tests for this component since it's fragile so fixes #705. Apparently we were showing the **Report Issue** button in `preview` mode too.
=> Fix ScholarshipCard issue and add exhaustive tests

src/components/FilterPanel.jsx, src/components/MajorFilter.jsx
Expands the major filter accordion by default
2. view scholarships
3. first filter accordion should be expanded
=> Expanded first filter accordion by default

.github/workflows/ci.yml
This seems to be the cause per https://stackoverflow.com/questions/69692842/error-message-error0308010cdigital-envelope-routinesunsupported
=> Downgrade CI node version to 16

src/components/Header.tsx, src/components/HeaderNavMenu.tsx, src/theme.ts
- Made non-selected tabs a little more visible
- Added a couple missing aria-labels
This bumps up our Accessibility score from 90 to 99 on https://web.dev/measure/. 
1. Right click and click **Inspect**.
2. Select the **Lighthouse** tab.
3. Click **Generate report**.
4. Repeat these steps for https://dreamscholars.org.
5. Compare the accessibility results and see improvements.
=> Address primary accessibility issues

src/components/ShareDialog.tsx
Just noticed when you click **Share** on a scholarship it only shares the link for whatever social media you click. We should _at least_ share a title too. Maybe we can even share a description too later.
1. Find a scholarship and click on it.
2. Try sharing it via Email, Facebook, etc.
3. Make sure the title is there.
=> Improve sharing by adding titles/subjects

src/App.jsx, src/pages/PublicHome.tsx
This fixes two issues related to page load experience (#1102):
- `<Footer>` _should_ be outside of the content-wrap `<div>` so that the Flexbox container can push it away from content. I messed this up in a prior PR.
- But keep `<Footer>` _inside_ the same `<Suspense>` so it doesn't get rendered before the main content.
2. Refresh the page (maybe with simulated slow speeds).
3. The footer should not appear before the main content
4. Zoom out the most you can.
5. The footer should stay at the very bottom.
6. Compare these behaviors with what we currently have at https://dreamscholars.org to see the difference.
=> Move Header and Footer out of content-wrap div

src/components/ScholarshipCard.tsx, src/components/ShowMoreScholarships.jsx
Fixes #1085.
Also added missing translation for `browse scholarships` button
2. click on a schoalrship
3. view the more scholarships section at the bottom
4. should all be of consistent size & not show lint or last updated text
=> hide lint issues and last modified in moreScholarships

package.json, src/firestore.rules.test.ts, src/models/Scholarships.test.ts, src/models/base/FirestoreCollection.test.ts, src/models/base/FirestoreModel.test.ts, src/models/base/FiretoreModelList.ts
Originally we added `--detectOpenHandles` because there were statements about it in the test runs. However, it never gives us anything useful. I did however track down that the tests that supposedly leak open handles are in `src/models`, particularly around interacting with Firestore (see #1174 for context).
Anyhow, it turns out the issue was the `@jest-environment node`. Removing that allows us to run `yarn test` without any complaints about leaked handles.
Also with this, the validation test check might be faster (at least it is on my machine).
=> Address --detectOpenHandles issue so test check runs faster
